# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/techlab_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Magia de Hibernate (update = crea o actualiza las tablas si no existen)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081